### ISSUE TITLE
automatic loading of CasperJS

### ISSUE THREAD

**Issue by yegor256** [linsolas/casperjs-runner-maven-plugin#13]
Would be convenient to have an ability to load `casperjs` automatically. It is just one file, should not be difficult.

**Comment by bguerin** [comment]
Hi !

Sorry for all this silent time !
CasperJS is not dead, neither it's maven plugin !
I just joined the CasperJs community : https://github.com/casperjs, and I will now work on the maven plugin directly from here : https://github.com/casperjs/casperjs-runner-maven-plugin
So feel free to reopen an issue there and I will see what I can do for this !
